jpush/jpush-docs

zh/docs/client/im_sdk_js.md
zh/mkdocs.yml

jpush docs merge request

---

zh/docs/client/android_tutorials.md

修改自定义通知栏样式中的代码示例

---

zh/docs/guideline/ios_guide.md

修改iOS Push r2.1.5 集成文档，增加IDFA 说明

修改iOS Push r2.1.5 集成文档，增加IDFA 说明

---

zh/docs/guideline/android_guide.md

update android-push-guide 2.1.3

update android-push-guide 2.1.3

---

zh/docs/guideline/ios_guide.md

JPush iOS 2.1.5 集成文档更新

---

zh/docs/guideline/android_guide.md

update package description.

---

zh/docs/client/im_sdk_ios.md

modify no disturb and event msg api description

---

zh/docs/resources.md

update ios download add

---

zh/docs/client/ios_api.md

219新增获取registrationID的接口说明

---

zh/docs/client/ios_sdk.md

JPushSDK在iOS 10上的适配说明

---

zh/docs/client/android_api.md

add collect and report the application crash logs api guide

---

zh/docs/client/ios_api.md

修改官方接口文档排版

---

zh/docs/client/im_sdk_ios.md

ios-im-sdk 文件和地理位置消息接口

---

zh/JMessage/docs/client/im_sdk_android.md

修复免打扰链接描述错误

---

zh/JSMS/docs/client/Android_SMS_SDK.md

更新android-jsms 文档(版本:1.1.0)

---

zh/JMessage/docs/client/im_sdk_ios.md

添加setFromName的接口

---

zh/JPush/docs/client/Android/android_guide.md

删除 MyReceiver 中无用的 action，以免干扰用户。

delete useless action in AndroidManifest

---

zh/JPush/docs/client/iOS/ios_guide_new.md

修改创建应用链接url

---

zh/JPush/docs/client/iOS/ios_guide_new.md

update parameters description in init code

---

zh/JPush/docs/client/iOS/ios_api.md
zh/JPush/docs/client/iOS/ios_cer_guide.md
zh/JPush/docs/client/iOS/ios_guide_new.md

修改文档内链接跳转错误，和库文件误导说明。

---

zh/JAnalytics/docs/client/android_api.md

update janalytics docs about countEvent

---

zh/themes/readthedocs/js/jpush.js

modify style

---

zh/JMessage/docs/client/im_errorcode_ios.md

添加缺少的iOS端错误码信息

---

zh/JAnalytics/docs/client/android_guide.md
zh/JPush/docs/client/Android/android_guide.md

fix bugs about android guide docs

---

zh/Index/jiguang/js/jpush.js
zh/themes/readthedocs/js/jpush.js

modify style compatible mobile phone

modify style compatible mobile phone

---

zh/JPush/docs/client/Android/android_guide.md

delete unnecessary text.

---

zh/JMessage/docs/client/jmessage_ios_guide.md

jmessage ios sdk v3 集成指南

---

zh/JMessage/docs/client/im_sdk_ios.md

ios jmessage sdk 新增接口

---

zh/JPush/docs/client/Android/android_api.md

update android JPush api docs about notification features.

---

zh/JMessage/docs/client/jmessage_ios_guide.md

修改JMessage iOS 集成文档

---

zh/JPush/docs/client/Android/android_api.md
zh/JPush/docs/client/Android/android_senior.md

在android-api文档中新增MultiActionsNotificationBuilder说明
在android-senior文档中新增MultiActionsNotificationBuilder说明

修改jpush文档,新增MultiActionsNotificationBuilder相关说明信息

---

zh/JMessage/docs/client/im_sdk_ios.md

新增iOS JMessage 接口文档 内容

---

zh/JPush/docs/server/push/http_status_code.md

update hyperlink to twitter&wiki about http-response-code

---

zh/JPush/docs/resources.md

update php & ruby SDK version

---

zh/JPush/docs/client/Android/android_api.md
zh/JPush/docs/client/Android/android_guide.md

更新jpush-api和集成文档(v303)

---

zh/JPush/docs/client/Android/android_guide.md

更新jpush集成文档(v303).修改allprojects单词错误

更新jpush集成文档(v303)

---

zh/JPush/docs/server/push/rest_api_v3_push.md

update error code in PUSH API

---

zh/JPush/docs/updates.md

更新 iOS push 3.0.5 版本的 ChangeLog

update iOS push 3.0.5

---

zh/JPush/docs/resources.md

更新 google play 版本的下载链接到 3.0.3 版本

update android push 3.0.3 for google play

---

zh/JPush/docs/updates.md

更新 android push sdk 3.0.5 changelog

update android push sdk 3.0.5 changelog

---

zh/JPush/docs/server/push/rest_api_v3_push.md

update Push API ErrorCode description.

---

zh/JAnalytics/docs/client/android_api.md
zh/JAnalytics/docs/client/android_guide.md
zh/JPush/docs/client/Android/android_guide.md

更新jpush集成文档(v305)
更新janalytics集成文档和api文档(v111)

更新jpush集成文档(v305)

---

zh/JAnalytics/docs/client/android_guide.md

janalytics集成文档内容错误。未显示manifest配置内容

更新janalytics集成文档

---

zh/JSMS/docs/guideline/JSMS_consoleguide.md

update consoleguide about JSMS

---

zh/JPush/docs/server/push/rest_api_v3_push.md

update error code for RESTFul API

---

zh/janalytics/client/android_api.md

setDebugModel接口名称错误(已修改成setDebugMode)。
修改字符登陆->登录

修改接口名称。修改登陆->登录

---

zh/jsms/client/Android_SMS_SDK.md

修改短信初始化接口名称

---

zh/jpush/client/Android/android_api.md
zh/jpush/client/Android/android_guide.md

去除3.0.9的配置。

---

mkdocs.yml
zh/jpush/server/push/rest_api_admin_api_v1.md

add admin api to rest list.

---

zh/jsms/server/rest_api_jsms.md
zh/jsms/server/rest_api_summary.md

add code 50038、30039、50040、50041

voice_codes add param code and voice_lang

---

zh/jpush/updates.md

新增 Android Push SDK v3.0.9 的信息到版本更新文档上。

add version message to updates.md.

---

zh/jpush/client/Android/android_api.md
zh/jpush/client/Android/android_guide.md

更新 3.0.9 的集成文档和 api 文档

---

zh/janalytics/guideline/intro.md

update janalytics intro 404 url

update janalytics intro 404 url

---

zh/jpush/server/push/rest_api_push_schedule.md
zh/jpush/server/push/rest_api_v3_push.md

优化 schedule api 和 push api 中的描述。

optimize server api

---

zh/jpush/client/iOS/ios_guide_new.md

update description for notification service extension.

---

zh/jpush/server/push/rest_api_v3_push.md

optimize push api description

---

zh/jpush/client/Android/android_guide.md

fix doc bug about android_guide

---

zh/janalytics/client/android_api.md

修改统计sdk api文档接口错误

---

zh/jmessage/client/im_sdk_js_v2.md

web im sdk 2.4.0

---

zh/jpush/resources.md

fix download link for jpush .

---

zh/janalytics/resources.md
zh/jpush/resources.md
zh/jshare/resources.md
zh/jsms/resources.md

restore download link for JPush,Janalytics,Jsms,Jshare.

---

zh/jpush/server/push/rest_api_v3_report.md

report api 新增 apns 通知送达设备的统计项。

add apns received in report api.

---

zh/jpush/client/Android/android_guide.md

fix description about channel statistics.

---

zh/jpush/updates.md

更新 JPush Android SDK 3.1.0 的 changelog

update for JPush Android SDK 3.1.0

---

zh/jpush/resources.md

update google play version to 310.

---

zh/jpush/updates.md

fix description bug about update android jpush sdk 3.1.0

---

zh/jpush/updates.md

fix description bug about update android jpush sdk 3.0.9

---

zh/jpush/updates.md

修复更新文档上 android jpush sdk 2.1.0 版本的格式问题。

fix description bug about update android jpush sdk 2.1.0

---

zh/jpush/server/push/rest_api_v3_push.md

edit description about audience-tag,tag_and, tag_not.

---

mkdocs.yml
zh/index.md
zh/jsms/client/Android/android_api.md
zh/jsms/client/Android/android_guide.md

更新短信的目录结构。更新短信sdk文档

---

mkdocs.yml
zh/JSMS/client/iOS/ios_api.md
zh/JSMS/client/iOS/ios_guide.md
zh/index.md

修改iOS JSMS 文档结构

---

zh/JSMS/client/iOS/ios_guide.md

修改iOS JSMS短信文档图片引用问题

---

zh/jsms/resources.md

修改jsms超链接。

---

zh/jmessage/server/rest_api_im.md

增加跨应用增加删除聊天室成员接口，以及更正获得聊天室成员列表文档

增加跨应用增加删除聊天室成员接口，以及更正获得聊天室成员列表文档

---

zh/jpush/updates.md

update for JPush Android SDK 3.1.1.

---

zh/jpush/resources.md

发布 JPush Android SDK 3.1.1 GooglePlay 版本

update JPush Android SDK 3.1.1 for GooglePlay.

---

zh/jpush/client/Android/android_api.md
zh/jpush/client/Android/android_guide.md

修改jpush api文档。

---

zh/jpush/updates.md

update for JPush iOS SDK 3.0.8.

---

zh/janalytics/client/ios_api.md

支持统计1.2.0版本上线，添加用户维度描述

---

zh/janalytics/client/android_api.md

针对Android统计1.2.0版本，修改android统计api文档.

修改android统计api文档

---

zh/janalytics/updates.md

janalytics sdk 1.2.0 release, android/ios

janalytics sdk 1.2.0 release, android/ios

---

zh/jpush/server/push/rest_api_push_schedule.md
zh/jpush/server/push/rest_api_v3_device.md
zh/jpush/server/push/rest_api_v3_push.md
zh/jpush/server/push/rest_api_v3_report.md

update description about bjapi.

---

zh/jpush/server/push/server_overview.md

fix url about business contact.

---

zh/jpush/server/push/server_overview.md

update reference link error.

---

zh/jpush/client/Android/android_guide.md

增加DownloadProvider配置

---

zh/jpush/guideline/intro.md

update register link in jiguang docs.

---

zh/janalytics/client/android_guide.md

统计集成文档更新(增加WAKE_LOCK必要权限说明)

---

mkdocs.yml
zh/jsms/server/callback.md
zh/jsms/server/rest_api_jsms_sign.md

add rest_api_jsms_sign，update callback

update jsms server docs

---

zh/janalytics/client/android_api.md

1.setAnalyticsReportPeriod，identifyAccount，detachAccount接口增加Context参数
2.增加1005错误码：未初始化时调用接口告知用户

统计1.2.1 API文档更新

---

zh/janalytics/client/android_api.md

Reverts jpush/jpush-docs#746
sdk 暂未上线，先revert

Revert "统计1.2.1 API文档更新"

---

zh/jpush/client/iOS/ios_cer_guide.md

fix bug about ios cert doc.

---

zh/jpush/server/push/rest_api_v3_push.md

update push-sms_ docs for template.

---

zh/jpush/server/push/rest_api_v3_push.md

update description about push-sms.

---

zh/jpush/server/push/rest_api_v3_push.md

update sms_message description in push api.

---

zh/jpush/updates.md

update for JPush iOS 3.0.9

---

zh/jpush/client/iOS/ios_api.md
zh/jpush/client/iOS/ios_guide_new.md

iOS JPush 3.0.9不依赖token可以登录，自定义消息增加messageID回调

---

zh/jpush/client/iOS/ios_api.md

update description about iOS Push SDK error code

---

zh/jpush/updates.md

更新 Android Push SDK 3.1.2 changelog

update changelog about Android JPush SDK 3.1.2.

---

zh/jpush/guideline/push-SMS-intro.md
zh/jpush/server/push/rest_api_v3_device.md
zh/jpush/server/push/rest_api_v3_report.md
zh/jpush/server/push/server_overview.md

update link about business contact in push docs.

---

zh/jpush/client/iOS/ios_guide_new.md

使用 ios extension 的文档描述中，提醒开发者添加两个 framework 文件。

update description about ios_extension

---

zh/jpush/client/iOS/ios_api.md

update iOS page flow api

---

zh/jpush/client/Android/android_guide.md

在 JPush Android 集成文档中添加 FCM 的描述。

add FCM description in JPush Docs.

---

zh/jpush/updates.md

update Android JPush SDK 3.1.3

---

en/docs/jsms/client/Android/android_api.md
en/docs/jsms/client/Android/android_guide.md

Finish JSMS Android docs

---

en/docs/janalytics/client/android_api.md
en/docs/janalytics/client/android_guide.md
en/docs/janalytics/client/android_sdk.md
en/docs/jshare/client/Android/android_api.md
en/docs/jshare/client/Android/android_sdk.md
en/docs/jshare/client/Android/android_sdk_faq.md
en/docs/jshare/client/Android/jshare_errorcode.md

Finish JAnalytics and JShare Android docs

Finish JAnalytics and JShare Android docs

---

zh/jpush/client/Android/android_api.md

fix reference v2 push api to v3

fix reference v2 push api to v3

---

zh/jshare/client/Android/android_sdk.md

Lijianmaster

---

zh/janalytics/resources.md

fix error link

---

zh/janalytics/resources.md

fix quickapp sdk download link

fix quickapp sdk download link

---

zh/janalytics/client/quickapp_api.md
zh/janalytics/client/quickapp_guide.md

fix quickapp janalytics sdk api and guide error

fix quickapp janalytics sdk api and guide error

---

zh/janalytics/updates.md

updates janalytics info

---

zh/jpush/client/Android/android_guide.md
zh/jshare/client/Android/android_api.md
zh/jshare/client/Android/android_sdk.md

JShare and JPush document update

share and push document completion update

---

zh/jpush/client/Android/android_guide.md
zh/jpush/updates.md

release  jpush android 3.1.6

---

zh/jmessage/client/im_errorcode_server.md

增加JMessage 后台错误码

---

zh/index.md
zh/jiot/server/restapi.md
zh/jiot/server/restapi_intro.md

 规范接口定义。修改频率限制

---

zh/jiot/server/restapi.md

 修改返回值，json结构

---

zh/jiot/client/android_sdk_api.md
zh/jiot/resources.md

 修复文档标题baugbug

---

mkdocs.yml
zh/jmessage/client/im_errorcode_ios.md

补充一个用户问道的错误提示

---

zh/janalytics/updates.md

no message
